# Generated by Django 2.1 on 2018-08-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PGA_Comp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('par_total', models.IntegerField(blank=True, default=None, null=True)),
                ('distance_total', models.IntegerField(blank=True, default=None, null=True)),
                ('purse_total', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('champ', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
