# Generated by Django 2.1 on 2018-08-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pga_comp',
            name='distance_total',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
