# Generated by Django 2.1 on 2018-08-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0002_auto_20180820_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGA_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='none', max_length=4, null=True)),
                ('name', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('to_par', models.IntegerField(blank=True, default=None, null=True)),
                ('current_round', models.IntegerField(blank=True, default=None, null=True)),
                ('thru', models.CharField(blank=True, default='none', max_length=20, null=True)),
                ('round1', models.IntegerField(blank=True, default=None, null=True)),
                ('round2', models.IntegerField(blank=True, default=None, null=True)),
                ('round3', models.IntegerField(blank=True, default=None, null=True)),
                ('round4', models.IntegerField(blank=True, default=None, null=True)),
                ('total_score', models.IntegerField(blank=True, default=None, null=True)),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golf.PGA_Comp')),
            ],
        ),
    ]
