# Generated by Django 2.1 on 2018-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0003_pga_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pga_event',
            name='current_round',
            field=models.CharField(blank=True, default='none', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pga_event',
            name='round1',
            field=models.CharField(blank=True, default='none', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pga_event',
            name='round2',
            field=models.CharField(blank=True, default='none', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pga_event',
            name='round3',
            field=models.CharField(blank=True, default='none', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pga_event',
            name='round4',
            field=models.CharField(blank=True, default='none', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pga_event',
            name='to_par',
            field=models.CharField(blank=True, default='none', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pga_event',
            name='total_score',
            field=models.CharField(blank=True, default='none', max_length=4, null=True),
        ),
    ]
