# Generated by Django 2.1 on 2018-08-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFU_Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(auto_now_add=True)),
                ('home_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('away_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFU_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='none', max_length=4, null=True)),
                ('team', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('played', models.FloatField(blank=True, null=True)),
                ('win', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('draw', models.FloatField(blank=True, null=True)),
                ('points_for', models.FloatField(blank=True, null=True)),
                ('points_against', models.FloatField(blank=True, null=True)),
                ('points_difference', models.FloatField(blank=True, null=True)),
                ('try_bonus', models.FloatField(blank=True, null=True)),
                ('loss_bonus', models.FloatField(blank=True, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
