# Generated by Django 2.1 on 2018-08-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_union', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfu_fixtures',
            name='match_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
