# Generated by Django 2.1 on 2018-09-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_union', '0002_auto_20180828_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premier15Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.FloatField(blank=True, null=True)),
                ('home_team', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('match_date', models.DateField(blank=True, default=None, null=True)),
                ('away_team', models.CharField(blank=True, default='none', max_length=200, null=True)),
            ],
        ),
    ]
