# Generated by Django 2.1 on 2018-09-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_union', '0003_premier15fixtures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premier15Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.FloatField(blank=True, null=True)),
                ('home_team', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('home_score', models.FloatField(blank=True, null=True)),
                ('away_score', models.FloatField(blank=True, null=True)),
                ('away_team', models.CharField(blank=True, default='none', max_length=200, null=True)),
            ],
        ),
    ]
