# Generated by Django 2.1 on 2018-09-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rugby_union', '0005_auto_20180913_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premier15Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(blank=True, null=True)),
                ('home_team', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('won', models.IntegerField(blank=True, null=True)),
                ('draw', models.IntegerField(blank=True, null=True)),
                ('loss', models.IntegerField(blank=True, null=True)),
                ('points_for', models.IntegerField(blank=True, null=True)),
                ('points_against', models.IntegerField(blank=True, null=True)),
                ('points_difference', models.IntegerField(blank=True, null=True)),
                ('try_bonus', models.IntegerField(blank=True, null=True)),
                ('loss_bonus', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
