# Generated by Django 2.1 on 2018-08-17 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0003_auto_20180815_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='location',
            new_name='place',
        ),
    ]
