# Generated by Django 2.1 on 2018-08-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0004_auto_20180817_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='place',
            new_name='location',
        ),
    ]
