# Generated by Django 2.1 on 2018-08-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0007_person_something'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
