# Generated by Django 2.1 on 2018-08-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0008_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='name', max_length=200)),
                ('club', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('level', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('tournament_type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('winner_points', models.IntegerField(blank=True, default=None, null=True)),
                ('finalist_points', models.IntegerField(blank=True, default=None, null=True)),
                ('semi_points', models.IntegerField(blank=True, default=None, null=True)),
                ('appearance_points', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
