# Generated by Django 2.1 on 2018-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0009_mycomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycomp',
            name='appearance_points',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
