# Generated by Django 2.1 on 2018-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polo', '0013_auto_20180827_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycomp',
            name='comp_name',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
    ]
