# Generated by Django 2.1 on 2018-09-23 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EliteLeagueSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(blank=True, default=None, null=True)),
                ('home_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('away_team', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('score', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EliteLeagueTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, default='none', max_length=200, null=True)),
                ('points', models.FloatField(blank=True, null=True)),
                ('played', models.FloatField(blank=True, null=True)),
                ('win', models.FloatField(blank=True, null=True)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('pct', models.FloatField(blank=True, null=True)),
                ('goal_for', models.FloatField(blank=True, null=True)),
                ('goal_against', models.FloatField(blank=True, null=True)),
                ('streak', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
